"""
FFTベースの相関（畳み込み）を用いた動体検出スクリプト

template_vs_phase.pyのfft_cross_correlation_fullを使用して、
Template Matchingと同等の機能をFFTで実現します。

Generated by: Auto (Cursor AI Agent Router) - trainscanner2 FFT-based motion detection
"""

import cv2
import numpy as np
from trainscanner2.image.template_vs_phase import (
    phase_correlation,
    fft_cross_correlation_full,
)
from trainscanner2.image import _find_peaks, diffImage


def detect_motion_fft(video_path: str, frame1_idx: int = 0, frame2_idx: int = 1):
    """
    FFTベースの相関を用いて動体検出を実行する。

    Args:
        video_path: 動画ファイルのパス
        frame1_idx: 最初のフレームのインデックス（デフォルト: 0）
        frame2_idx: 2番目のフレームのインデックス（デフォルト: 1）
    """
    # 動画ファイルを開く
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"動画ファイルを開けませんでした: {video_path}")

    # フレームを読み込む
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame1_idx)
    ret1, frame1 = cap.read()
    if not ret1:
        raise ValueError(f"フレーム{frame1_idx}を読み込めませんでした")

    cap.set(cv2.CAP_PROP_POS_FRAMES, frame2_idx)
    ret2, frame2 = cap.read()
    if not ret2:
        raise ValueError(f"フレーム{frame2_idx}を読み込めませんでした")

    cap.release()

    # グレースケールに変換
    if len(frame1.shape) == 3:
        gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    else:
        gray1 = frame1

    if len(frame2.shape) == 3:
        gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
    else:
        gray2 = frame2

    print(f"=== FFTベースの動体検出: フレーム{frame1_idx} vs フレーム{frame2_idx} ===")
    print(f"画像1のサイズ: {gray1.shape}")
    print(f"画像2のサイズ: {gray2.shape}")
    print()

    # Phase Correlationで背景の移動量を検出
    print("--- Phase Correlation (背景の移動量を検出) ---")
    try:
        pc_shift, pc_response = phase_correlation(gray1, gray2)
        detected_background_shift = (pc_shift[0], pc_shift[1])  # (dx, dy)として保持
        # diffImage用の変位（90度回転を考慮）
        bg_shift_for_diff = (pc_shift[1], pc_shift[0])  # (dy, dx)に変換
        print(
            f"検出された背景の移動量 (dx, dy): ({pc_shift[0]:.2f}, {pc_shift[1]:.2f})"
        )
        print(
            f"diffImage用の変位 (x, y): ({bg_shift_for_diff[0]:.2f}, {bg_shift_for_diff[1]:.2f})"
        )
        print(f"相関値: {pc_response:.4f}")
    except Exception as e:
        print(f"Phase Correlation failed: {e}")
        detected_background_shift = (0.0, 0.0)
        bg_shift_for_diff = (0.0, 0.0)
    print()

    # 画像1をパディング（最大移動量50px）
    max_shift = 50
    h1, w1 = gray1.shape[:2]
    h2, w2 = gray2.shape[:2]

    # パディングサイズは最大移動量で十分
    padding_size = max_shift

    # 画像1をパディング（上下左右にpadding_size分）
    image1_padded = np.zeros(
        (h1 + 2 * padding_size, w1 + 2 * padding_size), dtype=gray1.dtype
    )
    image1_padded[
        padding_size : padding_size + h1, padding_size : padding_size + w1
    ] = gray1

    print(f"--- FFT Cross Correlation（画像2を画像1内で検索） ---")
    print(f"パディングサイズ: {padding_size}px (最大移動量{max_shift}px)")
    print(f"パディング後の画像1のサイズ: {image1_padded.shape}")
    print()

    # FFTベースの相関を実行（通常の相関、Template Matchingと同等）
    fft_corr_map = fft_cross_correlation_full(
        image1_padded, gray2, use_phase_only=False
    )

    # 相関マップの統計を計算（参考用）
    fft_map_min = float(np.min(fft_corr_map))
    fft_map_max = float(np.max(fft_corr_map))
    fft_map_mean = float(np.mean(fft_corr_map))
    fft_map_std = float(np.std(fft_corr_map))

    # _find_peaksで極大値を検出
    peak_positions = _find_peaks(fft_corr_map)

    # 検出されたピークをスコアでソート
    peaks = []
    for x, y in peak_positions:
        score = float(fft_corr_map[y, x])
        # パディングを考慮して位置を調整
        adjusted_x = x - padding_size
        adjusted_y = y - padding_size
        peaks.append(((adjusted_x, adjusted_y), (x, y), score))

    # スコアでソート
    peaks.sort(key=lambda x: x[2], reverse=True)

    print(f"相関マップ統計（参考）:")
    print(f"  min: {fft_map_min:.6f}")
    print(f"  max: {fft_map_max:.6f}")
    print(f"  mean: {fft_map_mean:.6f}")
    print(f"  std: {fft_map_std:.6f}")
    print()

    print(f"--- FFT Cross Correlation（複数ピーク検出） ---")
    print(f"検出されたピーク数: {len(peaks)}（閾値なし）")
    print("上位10個のピーク:")
    for i, ((adj_x, adj_y), (pad_x, pad_y), score) in enumerate(peaks[:10]):
        # 背景の移動量との差を計算
        bg_diff = abs(adj_x - detected_background_shift[0]) + abs(
            adj_y - detected_background_shift[1]
        )
        peak_type = "背景" if bg_diff < 5 else "前景候補"
        print(
            f"  {i+1}. 位置（画像1座標系）: ({adj_x:.1f}, {adj_y:.1f}), "
            f"スコア: {score:.6f}, 背景との差: {bg_diff:.2f}px [{peak_type}]"
        )
    print()

    # 可視化
    print("--- 可視化 ---")
    # 画像1と画像2を表示
    cv2.imshow("Frame 1 (Background + Foreground)", gray1)
    cv2.imshow("Frame 2 (Shifted Background + Moved Foreground)", gray2)

    # 相関マップを可視化
    fft_colored = cv2.applyColorMap(
        (
            (fft_corr_map - np.min(fft_corr_map))
            / (np.max(fft_corr_map) - np.min(fft_corr_map) + 1e-10)
            * 255
        ).astype(np.uint8),
        cv2.COLORMAP_JET,
    )

    # 複数のピークにマーカーを描画
    # 背景のピーク（青）- 最大スコアのピーク（通常は背景）
    if len(peaks) > 0:
        bg_peak = peaks[0]
        bg_pad_x, bg_pad_y = bg_peak[1]
        cv2.circle(fft_colored, (bg_pad_x, bg_pad_y), 5, (255, 0, 0), 2)  # 青
        cv2.putText(
            fft_colored,
            "Background",
            (bg_pad_x + 10, bg_pad_y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.4,
            (255, 0, 0),
            1,
        )

    # 上位ピークにマーカーを描画（緑）
    for i, ((adj_x, adj_y), (pad_x, pad_y), score) in enumerate(peaks[:8]):
        if i > 0:  # 背景以外
            cv2.circle(fft_colored, (pad_x, pad_y), 5, (0, 255, 0), 2)  # 緑
            cv2.putText(
                fft_colored,
                f"P{i+1}",
                (pad_x + 10, pad_y + i * 15),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.4,
                (0, 255, 0),
                1,
            )

    cv2.imshow("FFT Cross Correlation Result", fft_colored)

    # 第1位から第8位までのピークで単純差分を表示
    print("--- 上位8ピークの単純差分表示 ---")
    for i, ((adj_x, adj_y), (pad_x, pad_y), score) in enumerate(peaks[:8]):
        # 90度回転を考慮して変位の順序を入れ替える
        shift_x = adj_y  # y方向の変位をx方向に
        shift_y = adj_x  # x方向の変位をy方向に

        # 単純差分を計算（diffImageのdiffモードを使用）
        simple_diff = diffImage(
            gray1,
            gray2,
            shift_x,
            shift_y,
            mode="diff",
        )

        # カラーマップで可視化
        diff_colored = cv2.applyColorMap(simple_diff, cv2.COLORMAP_JET)

        # ピーク情報を画像に描画
        cv2.putText(
            diff_colored,
            f"Peak {i+1}: pos=({adj_x:.1f}, {adj_y:.1f}), score={score:.6f}",
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )
        cv2.putText(
            diff_colored,
            f"Shift: ({shift_x:.1f}, {shift_y:.1f})",
            (10, 60),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )

        cv2.imshow(f"FFT Simple Diff - Peak {i+1}", diff_colored)
        print(
            f"  Peak {i+1}: 位置=({adj_x:.1f}, {adj_y:.1f}), シフト=({shift_x:.1f}, {shift_y:.1f}), スコア={score:.6f}"
        )
    print()

    print("キーを押すとウィンドウを閉じます...")
    cv2.waitKey(0)
    cv2.destroyAllWindows()


if __name__ == "__main__":
    video_path = "/Users/matto/Dropbox/ArtsAndIllustrations/Stitch tmp2/TrainScannerWorkArea/Freight/1167Tanker/IMG_1167.MOV"
    detect_motion_fft(video_path, frame1_idx=100, frame2_idx=101)
