"""
動画ファイルで動体検出を行うスクリプト

template_vs_phase.pyのmain()を参考に、実際の動画で動体検出を実行します。
現時点では、matchTemplateによる検出のみを実装しています。

Generated by: Auto (Cursor AI Agent Router) - trainscanner2 motion detection implementation
"""

import cv2
import numpy as np
from trainscanner2.image.template_vs_phase import phase_correlation, template_matching
from trainscanner2.image import _find_peaks, diffImage


def detect_motion_in_video(video_path: str, frame1_idx: int = 0, frame2_idx: int = 1):
    """
    動画ファイルの指定されたフレーム間で動体検出を実行する。

    Args:
        video_path: 動画ファイルのパス
        frame1_idx: 最初のフレームのインデックス（デフォルト: 0）
        frame2_idx: 2番目のフレームのインデックス（デフォルト: 1）
    """
    # 動画ファイルを開く
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"動画ファイルを開けませんでした: {video_path}")

    # フレームを読み込む
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame1_idx)
    ret1, frame1 = cap.read()
    if not ret1:
        raise ValueError(f"フレーム{frame1_idx}を読み込めませんでした")

    cap.set(cv2.CAP_PROP_POS_FRAMES, frame2_idx)
    ret2, frame2 = cap.read()
    if not ret2:
        raise ValueError(f"フレーム{frame2_idx}を読み込めませんでした")

    cap.release()

    # グレースケールに変換
    if len(frame1.shape) == 3:
        gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    else:
        gray1 = frame1

    if len(frame2.shape) == 3:
        gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
    else:
        gray2 = frame2

    print(f"=== 動体検出: フレーム{frame1_idx} vs フレーム{frame2_idx} ===")
    print(f"画像1のサイズ: {gray1.shape}")
    print(f"画像2のサイズ: {gray2.shape}")
    print()

    # Phase Correlationで背景の移動量を検出
    print("--- Phase Correlation (背景の移動量を検出) ---")
    try:
        pc_shift, pc_response = phase_correlation(gray1, gray2)
        # cv2.phaseCorrelateは(dx, dy)を返すが、これは画像座標系での変位
        # diffImageは(x, y)の順で変位を受け取る
        # 画像が90度回転して表示されている場合、変位の順序を入れ替える必要がある
        # NumPy配列は(height, width) = (y, x)の順なので、
        # phaseCorrelateの(dx, dy)は実際には(x方向, y方向)の変位
        # しかし、画像が90度回転している場合、表示上の横方向 = NumPy配列のy方向
        # 表示上の縦方向 = NumPy配列のx方向
        # したがって、diffImageに渡す変位は(dy, dx)の順にする必要がある
        detected_background_shift = (pc_shift[0], pc_shift[1])  # (dx, dy)として保持
        # diffImage用の変位（90度回転を考慮）
        bg_shift_for_diff = (pc_shift[1], pc_shift[0])  # (dy, dx)に変換
        print(
            f"検出された背景の移動量 (dx, dy): ({pc_shift[0]:.2f}, {pc_shift[1]:.2f})"
        )
        print(
            f"diffImage用の変位 (x, y): ({bg_shift_for_diff[0]:.2f}, {bg_shift_for_diff[1]:.2f})"
        )
        print(f"相関値: {pc_response:.4f}")
    except Exception as e:
        print(f"Phase Correlation failed: {e}")
        detected_background_shift = (0.0, 0.0)
        bg_shift_for_diff = (0.0, 0.0)
    print()

    # 画像1をパディング（最大移動量50px）
    max_shift = 50
    h1, w1 = gray1.shape[:2]
    h2, w2 = gray2.shape[:2]

    # パディングサイズは最大移動量で十分
    padding_size = max_shift

    # 画像1をパディング（上下左右にpadding_size分）
    image1_padded = np.zeros(
        (h1 + 2 * padding_size, w1 + 2 * padding_size), dtype=gray1.dtype
    )
    image1_padded[
        padding_size : padding_size + h1, padding_size : padding_size + w1
    ] = gray1

    print(f"--- Template Matching（画像2を画像1内で検索） ---")
    print(f"パディングサイズ: {padding_size}px (最大移動量{max_shift}px)")
    print(f"パディング後の画像1のサイズ: {image1_padded.shape}")
    print()

    # 画像2をテンプレートとして、パディングされた画像1内でTemplate Matchingを実行
    tm_result = cv2.matchTemplate(image1_padded, gray2, cv2.TM_CCOEFF_NORMED)

    # 複数のピークを検出
    peak_positions = _find_peaks(tm_result)
    peaks = []
    for x, y in peak_positions:
        score = float(tm_result[y, x])
        # パディングを考慮して位置を調整
        adjusted_x = x - padding_size
        adjusted_y = y - padding_size
        peaks.append(((adjusted_x, adjusted_y), (x, y), score))

    # スコアでソート
    peaks.sort(key=lambda x: x[2], reverse=True)

    print(f"--- Template Matching（複数ピーク検出） ---")
    print(f"検出されたピーク数: {len(peaks)}")
    print("上位10個のピーク:")
    for i, ((adj_x, adj_y), (pad_x, pad_y), score) in enumerate(peaks[:10]):
        # 背景の移動量との差を計算
        bg_diff = abs(adj_x - detected_background_shift[0]) + abs(
            adj_y - detected_background_shift[1]
        )
        peak_type = "背景" if bg_diff < 5 else "前景候補"
        print(
            f"  {i+1}. 位置（画像1座標系）: ({adj_x:.1f}, {adj_y:.1f}), "
            f"スコア: {score:.4f}, 背景との差: {bg_diff:.2f}px [{peak_type}]"
        )
    print()

    # 前景の移動量を推定（背景の移動量と異なるピークを探す）
    print("--- 前景の移動量推定 ---")
    foreground_peaks = []
    for (adj_x, adj_y), _, score in peaks:
        bg_diff = abs(adj_x - detected_background_shift[0]) + abs(
            adj_y - detected_background_shift[1]
        )
        if bg_diff > 5:  # 背景の移動量と5px以上の差がある
            foreground_peaks.append(((adj_x, adj_y), score, bg_diff))

    if len(foreground_peaks) > 0:
        # スコアでソート
        foreground_peaks.sort(key=lambda x: x[1], reverse=True)
        best_foreground = foreground_peaks[0]
        detected_x, detected_y = best_foreground[0]

        print(f"最良の前景候補:")
        print(f"  位置（画像1座標系）: ({detected_x:.1f}, {detected_y:.1f})")
        print(f"  スコア: {best_foreground[1]:.4f}")
        print(f"  背景との差: {best_foreground[2]:.2f}px")
    else:
        print("前景候補が見つかりませんでした")
        detected_x, detected_y = None, None
    print()

    # 可視化
    print("--- 可視化 ---")
    # 画像1と画像2を表示
    cv2.imshow("Frame 1 (Background + Foreground)", gray1)
    cv2.imshow("Frame 2 (Shifted Background + Moved Foreground)", gray2)

    # 第1位から第8位までのピークで単純差分を表示
    print("--- 上位8ピークの単純差分表示 ---")
    for i, ((adj_x, adj_y), (pad_x, pad_y), score) in enumerate(peaks[:8]):
        # 90度回転を考慮して変位の順序を入れ替える
        shift_x = adj_y  # y方向の変位をx方向に
        shift_y = adj_x  # x方向の変位をy方向に

        # 単純差分を計算（diffImageのdiffモードを使用）
        simple_diff = diffImage(
            gray1,
            gray2,
            shift_x,
            shift_y,
            mode="diff",
        )

        # カラーマップで可視化
        diff_colored = cv2.applyColorMap(simple_diff, cv2.COLORMAP_JET)

        # ピーク情報を画像に描画
        cv2.putText(
            diff_colored,
            f"Peak {i+1}: pos=({adj_x:.1f}, {adj_y:.1f}), score={score:.4f}",
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )
        cv2.putText(
            diff_colored,
            f"Shift: ({shift_x:.1f}, {shift_y:.1f})",
            (10, 60),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )

        cv2.imshow(f"Simple Diff - Peak {i+1}", diff_colored)
        print(
            f"  Peak {i+1}: 位置=({adj_x:.1f}, {adj_y:.1f}), シフト=({shift_x:.1f}, {shift_y:.1f}), スコア={score:.4f}"
        )
    print()

    # diffImageで変位を可視化（背景の変位）
    # 90度回転を考慮して変位の順序を入れ替える
    if bg_shift_for_diff[0] != 0.0 or bg_shift_for_diff[1] != 0.0:
        bg_diff_image = diffImage(
            gray1,
            gray2,
            bg_shift_for_diff[0],  # x方向の変位（表示上の横方向）
            bg_shift_for_diff[1],  # y方向の変位（表示上の縦方向）
            mode="diff",
        )
        cv2.imshow("Background Motion Diff", bg_diff_image)

        bg_stack_image = diffImage(
            gray1,
            gray2,
            bg_shift_for_diff[0],
            bg_shift_for_diff[1],
            mode="stack",
        )
        cv2.imshow("Background Motion Stack", bg_stack_image)

    # 前景の変位を可視化（背景の変位との差分として計算）
    if detected_x is not None and detected_y is not None:
        # 前景の変位量 = 検出された位置 - 背景の変位
        # detected_x, detected_yは画像座標系での位置
        # 90度回転を考慮して変位の順序を入れ替える
        foreground_shift_x = (
            detected_y - detected_background_shift[1]
        )  # y方向の変位をx方向に
        foreground_shift_y = (
            detected_x - detected_background_shift[0]
        )  # x方向の変位をy方向に
        # 前景の変位でdiffImageを作成（背景補正済み）
        fg_diff_image = diffImage(
            gray1, gray2, foreground_shift_x, foreground_shift_y, mode="diff"
        )
        cv2.imshow("Foreground Motion Diff (relative to background)", fg_diff_image)

        fg_stack_image = diffImage(
            gray1, gray2, foreground_shift_x, foreground_shift_y, mode="stack"
        )
        cv2.imshow("Foreground Motion Stack (relative to background)", fg_stack_image)

    # 相関マップを可視化
    tm_colored = cv2.applyColorMap(
        (
            (tm_result - np.min(tm_result))
            / (np.max(tm_result) - np.min(tm_result) + 1e-10)
            * 255
        ).astype(np.uint8),
        cv2.COLORMAP_JET,
    )

    # 複数のピークにマーカーを描画
    # 背景のピーク（青）- 最大スコアのピーク（通常は背景）
    if len(peaks) > 0:
        bg_peak = peaks[0]
        bg_pad_x, bg_pad_y = bg_peak[1]
        cv2.circle(tm_colored, (bg_pad_x, bg_pad_y), 5, (255, 0, 0), 2)  # 青
        cv2.putText(
            tm_colored,
            "Background",
            (bg_pad_x + 10, bg_pad_y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.4,
            (255, 0, 0),
            1,
        )

    # 前景候補のピーク（緑）
    if len(foreground_peaks) > 0:
        for i, ((adj_x, adj_y), score, bg_diff) in enumerate(foreground_peaks[:3]):
            # パディング座標系に変換
            pad_x = int(adj_x + padding_size)
            pad_y = int(adj_y + padding_size)
            if 0 <= pad_x < tm_result.shape[1] and 0 <= pad_y < tm_result.shape[0]:
                cv2.circle(tm_colored, (pad_x, pad_y), 5, (0, 255, 0), 2)  # 緑
                cv2.putText(
                    tm_colored,
                    f"Foreground{i+1}",
                    (pad_x + 10, pad_y + i * 15),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.4,
                    (0, 255, 0),
                    1,
                )

    cv2.imshow("Template Matching Result (Frame2 in Padded Frame1)", tm_colored)

    # 結果を画像上に描画（diffImageの結果に描画）
    # 背景の変位でdiffImageを作成（90度回転を考慮）
    if bg_shift_for_diff[0] != 0.0 or bg_shift_for_diff[1] != 0.0:
        result_image = diffImage(
            gray1,
            gray2,
            bg_shift_for_diff[0],
            bg_shift_for_diff[1],
            mode="stack",
        )
        result_image = cv2.cvtColor(result_image, cv2.COLOR_GRAY2BGR)
    else:
        result_image = gray2.copy()
        result_image = cv2.cvtColor(result_image, cv2.COLOR_GRAY2BGR)

    # 背景の位置を描画（青）
    # cv2.rectangleは(x, y)の順で座標を取る
    if len(peaks) > 0:
        bg_adj_x, bg_adj_y = peaks[0][0]
        bg_adj_x, bg_adj_y = int(bg_adj_x), int(bg_adj_y)
        # 画像のサイズを確認（縦長画像の場合、w1 < h1）
        if 0 <= bg_adj_x < w1 and 0 <= bg_adj_y < h1:
            # cv2.rectangleは(x, y)の順、右下の座標も(x, y)の順
            cv2.rectangle(
                result_image,
                (bg_adj_x, bg_adj_y),
                (min(bg_adj_x + w2, w1), min(bg_adj_y + h2, h1)),
                (255, 0, 0),
                2,
            )
            cv2.putText(
                result_image,
                f"Background: ({detected_background_shift[0]:.1f}, {detected_background_shift[1]:.1f})",
                (bg_adj_x, max(0, bg_adj_y - 5)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.4,
                (255, 0, 0),
                1,
            )

    # 前景候補の位置を描画（緑）
    if detected_x is not None and detected_y is not None:
        detected_x, detected_y = int(detected_x), int(detected_y)
        if 0 <= detected_x < w1 and 0 <= detected_y < h1:
            cv2.rectangle(
                result_image,
                (detected_x, detected_y),
                (min(detected_x + w2, w1), min(detected_y + h2, h1)),
                (0, 255, 0),
                2,
            )
            cv2.putText(
                result_image,
                f"Foreground",
                (detected_x, max(0, detected_y - 5)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.4,
                (0, 255, 0),
                1,
            )

    cv2.imshow("Detection Result", result_image)

    print("キーを押すとウィンドウを閉じます...")
    cv2.waitKey(0)
    cv2.destroyAllWindows()


if __name__ == "__main__":
    video_path = "/Users/matto/Dropbox/ArtsAndIllustrations/Stitch tmp2/TrainScannerWorkArea/Freight/1167Tanker/IMG_1167.MOV"
    detect_motion_in_video(video_path, frame1_idx=0, frame2_idx=1)
