[project]
name = "trainscanner2"
version = "2.0b1"
description = "TrainScanner2: A tool for scanning and analyzing train videos."
authors = [
    {name = "vitroid", email = "vitroid@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry]
packages = [{include = "trainscanner2"}]
include = ["ts2undump.py"]

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
pyperbox = ">=0.1.1"
pykalman = ">=0.10.2"
matplotlib = "*"
numpy = "*"
pyqt6 = ">=6.0.0"
tqdm = "^4.67.1"
opencv-python = "^4.8.0"
# Local dependencies - these must be on PyPI for a successful PyPI release
yt-dlp = "^2025.12.8"
click = "^8.3.1"

[tool.poetry.scripts]
trainscanner2 = "trainscanner2.trainscanner2:main"
ts2undump = "ts2undump:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
